# Generated by Django 3.2.7 on 2021-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='u_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('PayPal', 'PayPal')], default='Cash On Delivery', max_length=20),
        ),
    ]
